// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const Services = {}; loadServices();

module.exports = {
  // An array of folders (excluding subfolders) where your tests are located;
  // if this is not specified, the test source must be passed as the second argument to the test runner.
  src_folders: ["__tests__/e2e"],

  // See https://nightwatchjs.org/guide/working-with-page-objects/
  page_objects_path: '',

  // See https://nightwatchjs.org/guide/extending-nightwatch/#writing-custom-commands
  custom_commands_path:  '',

  // See https://nightwatchjs.org/guide/extending-nightwatch/#writing-custom-assertions
  custom_assertions_path: '',

  // See https://nightwatchjs.org/guide/#external-globals
  globals_path : '',
  // webdriver: {
  //   "start_process": true,
  //   "server_path": "node_modules/.bin/chromedriver",
  //   "port": 9515
  // },

  test_settings: {
      default: {
        //disable_error_log: false,
        //launch_url: 'https://nightwatchjs.org',

        // screenshots: {
        //   enabled: false,
        //   path: 'screens',
        //   on_failure: true
        // },
        desiredCapabilities: {
          browserName : 'chrome'
        },
      },

      selenium: {
        // Selenium Server is running locally and is managed by Nightwatch
        selenium: {
          start_process: true,
          port: 4444,
          server_path: "./node_modules/selenium-server/lib/runner/selenium-server-standalone-3.141.59.jar",
          //(Services.seleniumServer ? Services.seleniumServer.path : ''),
          cli_args: {

            'webdriver.chrome.driver': "./node_modules/.bin/chromedriver"
            //(Services.chromedriver ? Services.chromedriver.path : '')
          }
          ,check_process_delay: 5000,
        }
      },

      'selenium.chrome': {
        extends: 'selenium',
        desiredCapabilities: {
          browserName: 'chrome',
          chromeOptions : {
            w3c: false
          }
        }
      }
    }
};

function loadServices() {
  try {
    Services.seleniumServer = require('selenium-server');
  } catch (err) {}

  try {
    Services.chromedriver = require('chromedriver');
  } catch (err) {}

  try {
    Services.geckodriver = require('geckodriver');
  } catch (err) {}
}
